import os
import io
import re
import uuid
from datetime import datetime
from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
from groq import Groq
from pypdf import PdfReader
from fpdf import FPDF


app = Flask(__name__)
CORS(app, resources={r"/*": {
    "origins": ["http://localhost:3000", "http://127.0.0.1:3000"],
    "methods": ["GET", "POST", "OPTIONS"],
    "allow_headers": ["Content-Type", "Authorization"]
}})


GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "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" \
"")
client = Groq(api_key=GROQ_API_KEY)
MAX_FILE_SIZE_MB = 10
report_store = {}


SYSTEM_PROMPT = (
    "You are ReadMed AI, a professional medical translator.\n"
    "Convert the raw medical report into a simple English summary.\n"
    "Use EXACTLY this structure. Do NOT use any emoji, symbols, or special characters.\n"
    "Use only plain letters, numbers, spaces, hyphens, pipes, and dots.\n\n"
    "---\n\n"
    "[PROFILE] PROFILE SUMMARY\n"
    "Name: [Name], Age: [Age], Hospital: [Hospital], Date: [Date], Doctor: [Doctor]\n"
    "(Write Not specified for any missing field.)\n\n"
    "---\n\n"
    "[OBSERVATIONS] KEY OBSERVATIONS\n\n"
    "| Parameter | Normal Range | Measured Value | Remark |\n"
    "|---|---|---|---|\n"
    "| [test name] | [range] | [value] | High or Low or Normal or Moderate |\n\n"
    "---\n\n"
    "[EXPLANATION] SIMPLE EXPLANATION\n"
    "Write 1-2 plain English sentences. No medical jargon.\n\n"
    "---\n\n"
    "[RISK] RISK INDICATORS\n"
    "- [Issue]: If left unmanaged, it could increase the risk of [Impact].\n"
    "(Write No significant risks found. if none apply.)\n\n"
    "---\n\n"
    "[INSIGHTS] WELLNESS INSIGHTS\n"
    "Write 1-2 sentences about the overall health outlook.\n\n"
    "---\n\n"
    "[RECOMMENDATIONS] RECOMMENDATIONS\n"
    "- [step 1]\n"
    "- [step 2]\n"
    "- [step 3]\n"
    "(Give 4-6 steps.)\n\n"
    "---\n\n"
    "[LIFESTYLE] LIFESTYLE SUGGESTIONS\n\n"
    "| Problem | Suggestion |\n"
    "|---|---|\n"
    "| [issue] | [tip] |\n\n"
    "---\n\n"
    "Disclaimer: This report is generated by ReadMed AI for informational purposes only. "
    "Always consult your doctor.\n\n"
    "STRICT RULES:\n"
    "1. NO emoji of any kind.\n"
    "2. NO Unicode symbols.\n"
    "3. Use only plain ASCII text.\n"
    "4. Always include all 7 sections.\n"
    "5. Always start each section with its [LABEL] marker.\n"
)




def to_ascii(text):
    """Remove every character that is not plain printable ASCII."""
    if not text:
        return ""
    return re.sub(r'[^\x20-\x7E\n\r\t]', '', text)




def extract_text_from_pdf(file):
    reader = PdfReader(file)
    text = ""
    for page in reader.pages:
        extracted = page.extract_text()
        if extracted:
            text += extracted + "\n"
    return text.strip()




def build_prompt(raw_text, user_info):
    info = (
        "PATIENT INFO:\n"
        "Name: {}\nAge: {}\nGender: {}\n".format(
            user_info.get("name") or "Not specified",
            user_info.get("age") or "Not specified",
            user_info.get("gender") or "Not specified",
        )
    )
    if user_info.get("conditions"):
        info += "Conditions: {}\n".format(user_info["conditions"])
    if user_info.get("medications"):
        info += "Medications: {}\n".format(user_info["medications"])
    return "{}\nREPORT:\n{}\n\nGenerate the structured ReadMed AI report.".format(info, raw_text)




@app.after_request
def after_request(response):
    response.headers.add("Access-Control-Allow-Origin", "*")
    response.headers.add("Access-Control-Allow-Headers", "Content-Type,Authorization")
    response.headers.add("Access-Control-Allow-Methods", "GET,POST,OPTIONS")
    return response




@app.route('/<path:path>', methods=['OPTIONS'])
def options_handler(path):
    return '', 204




@app.route('/process', methods=['POST'])
def process_report():
    raw_text = ""


    if 'file' in request.files and request.files['file'].filename:
        file = request.files['file']
        file.seek(0, 2)
        if file.tell() / (1024 * 1024) > MAX_FILE_SIZE_MB:
            return jsonify({"success": False, "error": "File too large. Max 10MB."}), 413
        file.seek(0)
        if not file.filename.lower().endswith('.pdf'):
            return jsonify({"success": False, "error": "Only PDF files supported."}), 400
        try:
            raw_text = extract_text_from_pdf(file)
        except Exception as e:
            return jsonify({"success": False, "error": "Could not read PDF: {}".format(e)}), 400


    elif request.form.get("manual_text", "").strip():
        raw_text = request.form.get("manual_text", "").strip()


    if not raw_text:
        return jsonify({"success": False, "error": "No report content provided."}), 400


    raw_text = raw_text[:15000]


    user_info = {
        "name":        request.form.get("patient_name", "").strip(),
        "age":         request.form.get("patient_age", "").strip(),
        "gender":      request.form.get("patient_gender", "").strip(),
        "conditions":  request.form.get("known_conditions", "").strip(),
        "medications": request.form.get("medications", "").strip(),
    }


    try:
        result = client.chat.completions.create(
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user",   "content": build_prompt(raw_text, user_info)},
            ],
            model="llama-3.3-70b-versatile",
            temperature=0.3,
            max_tokens=2500,
        )
        # Strip ALL non-ASCII right at the source before storing
        explanation = to_ascii(result.choices[0].message.content)


        session_id = str(uuid.uuid4())
        report_store[session_id] = {
            "text":      explanation,
            "timestamp": datetime.now().isoformat(),
            "user_info": user_info,
        }
        if len(report_store) > 100:
            del report_store[next(iter(report_store))]


        return jsonify({"success": True, "explanation": explanation, "session_id": session_id})


    except Exception as e:
        print("[ERROR] {}".format(e))
        return jsonify({"success": False, "error": "AI processing failed: {}".format(e)}), 500




SECTION_MAP = {
    '[PROFILE]':         ('Profile Summary',       (15,  52,  96)),
    '[OBSERVATIONS]':    ('Key Observations',       (0,   121, 107)),
    '[EXPLANATION]':     ('Simple Explanation',     (230, 81,  0)),
    '[RISK]':            ('Risk Indicators',        (183, 28,  28)),
    '[INSIGHTS]':        ('Wellness Insights',      (74,  20,  140)),
    '[RECOMMENDATIONS]': ('Recommendations',        (27,  94,  32)),
    '[LIFESTYLE]':       ('Lifestyle Suggestions',  (13,  71,  161)),
}




def render_pdf(stored):
    # to_ascii called again as final guarantee - belt AND suspenders
    raw_text = to_ascii(stored['text'])
    user_info = stored.get('user_info', {})
    patient  = to_ascii(user_info.get('name', '') or 'N/A')


    pdf  = FPDF(orientation='P', unit='mm', format='A4')
    f    = 'Helvetica'
    pdf.set_auto_page_break(auto=True, margin=22)
    pdf.add_page()


    # Header band
    pdf.set_fill_color(15, 52, 96)
    pdf.rect(0, 0, 210, 44, 'F')
    pdf.set_fill_color(0, 188, 212)
    pdf.rect(0, 44, 210, 3, 'F')


    pdf.set_font(f, 'B', 24)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(14, 8)
    pdf.cell(0, 12, 'ReadMed AI', ln=True)


    pdf.set_font(f, '', 10)
    pdf.set_text_color(180, 220, 255)
    pdf.set_xy(14, 23)
    pdf.cell(0, 7, 'Your Medical Report - Simplified', ln=True)


    pdf.set_font(f, '', 9)
    pdf.set_text_color(140, 190, 240)
    pdf.set_xy(14, 33)
    date_str = datetime.now().strftime('%d %B %Y  |  %I:%M %p')
    pdf.cell(0, 7, 'Patient: {}   |   {}'.format(patient, date_str), ln=True)
    pdf.set_y(54)


    # Table state
    in_table      = False
    table_headers = []
    table_rows    = []


    def flush_table():
        nonlocal in_table, table_headers, table_rows
        if not table_headers:
            in_table = False
            return


        nc = len(table_headers)
        W  = 182
        cw = [52, 38, 38, 54] if nc == 4 else ([72, 110] if nc == 2 else [W // nc] * nc)


        # Header row
        pdf.set_fill_color(220, 230, 242)
        pdf.set_text_color(15, 52, 96)
        pdf.set_font(f, 'B', 9)
        pdf.set_x(14)
        for i, h in enumerate(table_headers):
            pdf.cell(cw[i] if i < len(cw) else 40, 8, h[:30], border=1, align='C', fill=True)
        pdf.ln()


        for ri, row in enumerate(table_rows):
            ru = ' '.join(row).upper()
            if 'HIGH' in ru or (' LOW' in ru and 'BELOW' not in ru):
                pdf.set_fill_color(255, 235, 235); pdf.set_text_color(160, 0, 0)
            elif 'MODERATE' in ru or 'BORDERLINE' in ru:
                pdf.set_fill_color(255, 253, 220); pdf.set_text_color(120, 80, 0)
            elif 'NORMAL' in ru:
                pdf.set_fill_color(235, 255, 240); pdf.set_text_color(10, 100, 40)
            elif ri % 2 == 0:
                pdf.set_fill_color(255, 255, 255); pdf.set_text_color(40, 40, 40)
            else:
                pdf.set_fill_color(246, 248, 252); pdf.set_text_color(40, 40, 40)


            pdf.set_font(f, '', 9)
            xs = 14; ys = pdf.get_y(); rh = 7


            for i, cv in enumerate(row):
                if i >= len(cw): continue
                cp = max(1, int(cw[i] / 2.2))
                rh = max(rh, max(1, -(-len(cv.strip()) // cp)) * 6)


            for i, cv in enumerate(row):
                if i >= len(cw): continue
                pdf.set_xy(xs, ys)
                pdf.multi_cell(
                    cw[i],
                    rh / max(1, len(cv.strip()) // max(1, int(cw[i] / 2.2)) + 1),
                    cv.strip(), border=1, align='L', fill=True
                )
                xs += cw[i]


            pdf.set_y(ys + rh)
            pdf.set_text_color(40, 40, 40)


        pdf.ln(4)
        in_table = False; table_headers = []; table_rows = []


    for raw_line in raw_text.split('\n'):
        # Strip backticks, hashes, asterisks, extra spaces
        line = re.sub(r'[`*#]', '', raw_line).strip()


        # Table row
        if '|' in line and line.startswith('|'):
            cells = [to_ascii(c.strip()) for c in line.strip('|').split('|')]
            if all(re.match(r'^[-:]+$', c.replace(' ', '')) for c in cells if c):
                continue
            if not in_table:
                in_table = True; table_headers = cells; table_rows = []
            else:
                if cells: table_rows.append(cells)
            continue
        else:
            if in_table: flush_table()


        if not line:
            pdf.ln(2)
            continue


        # Section header
        section_match = None
        for key, (title, color) in SECTION_MAP.items():
            if line.startswith(key) or key in line[:25]:
                section_match = (title, color)
                break


        if section_match:
            title, (r, g, b) = section_match
            pdf.ln(5)
            pdf.set_fill_color(r, g, b)
            pdf.set_text_color(255, 255, 255)
            pdf.set_font(f, 'B', 12)
            pdf.set_x(14)
            pdf.cell(182, 10, '  ' + title.upper(), ln=True, fill=True)
            # Accent underline
            pdf.set_fill_color(min(r + 30, 255), min(g + 30, 255), min(b + 30, 255))
            pdf.rect(14, pdf.get_y(), 182, 1.5, 'F')
            pdf.ln(4)


        elif line.startswith('---'):
            pdf.set_draw_color(210, 218, 228)
            pdf.set_line_width(0.3)
            pdf.line(14, pdf.get_y(), 196, pdf.get_y())
            pdf.ln(3)


        elif 'disclaimer' in line.lower() or 'informational purposes' in line.lower():
            pdf.ln(3)
            pdf.set_font(f, 'I', 8)
            pdf.set_text_color(130, 130, 140)
            pdf.set_x(14)
            pdf.multi_cell(182, 5, line, align='C')


        elif line.startswith('-'):
            pdf.set_font(f, '', 10)
            pdf.set_text_color(40, 40, 50)
            pdf.set_x(20)
            pdf.multi_cell(176, 6, line, align='L')
            pdf.ln(1)


        else:
            pdf.set_font(f, '', 10)
            pdf.set_text_color(50, 50, 60)
            pdf.set_x(14)
            pdf.multi_cell(182, 6, line, align='L')
            pdf.ln(1)


    if in_table:
        flush_table()


    # Footer
    pdf.set_y(-18)
    pdf.set_fill_color(15, 52, 96)
    pdf.rect(0, pdf.get_y(), 210, 20, 'F')
    pdf.set_font(f, '', 8)
    pdf.set_text_color(160, 200, 240)
    pdf.cell(0, 10,
             'ReadMed AI  |  For informational purposes only  |  Always consult a qualified doctor',
             align='C', ln=True)


    return bytes(pdf.output())




@app.route('/download-report', methods=['GET', 'POST'])
def download_report():
    sid = (
        request.args.get("session_id", "").strip()
        or (request.json or {}).get("session_id", "").strip()
        or request.form.get("session_id", "").strip()
    )
    if not sid or sid not in report_store:
        if report_store:
            sid = list(report_store.keys())[-1]
        else:
            return jsonify({"success": False, "error": "No report found. Generate one first."}), 404


    try:
        pdf_bytes = render_pdf(report_store[sid])
        fname = 'ReadMed_Report_{}.pdf'.format(datetime.now().strftime('%Y%m%d_%H%M'))
        return send_file(io.BytesIO(pdf_bytes), mimetype='application/pdf',
                         as_attachment=True, download_name=fname)
    except Exception as e:
        print("[ERROR] PDF: {}".format(e))
        return jsonify({"success": False, "error": "PDF generation failed: {}".format(e)}), 500




@app.route('/health', methods=['GET'])
def health_check():
    return jsonify({"status": "ok", "version": "5.0.0"})




@app.route('/latest-session', methods=['GET'])
def latest_session():
    if not report_store:
        return jsonify({"success": False, "error": "No reports yet."}), 404
    lid = list(report_store.keys())[-1]
    return jsonify({"success": True, "session_id": lid,
                    "timestamp": report_store[lid]["timestamp"]})




if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5001)
